### PR TITLE
Radio group fixes

### PR DESCRIPTION
**Pull request by Toshegg**
Connects to #12

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/16)

### CODE REVIEW

**Comment by Toshegg** [comment]
I will fix tests in the next commit

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-:-KwjRzsB9BiZpAfKjJn5:b-zbhzgq)*

**Comment by tomivirkki** [comment]
*[vaadin-radio-group.html, line 116 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-Kwm5R8GURiLfdtXGpqM:-Kwm5R8GURiLfdtXGpqN:b-7uz3zn) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/a2a97139b9e2c78260cc1f0544b6517ee6370b63/vaadin-radio-group.html#L116)):*
> ```HTML
> 
>         get _radioButtons() {
>           return Array.from(this.children)
> ```

Would it make sense not to require the radio buttons to be direct children and base types? Rather use `querySelectorAll('*')` and then filter the results by `instanceof Vaadin.RadioButtonElement`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16)*

**Comment by Toshegg** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-radio-group.html, line 116 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-Kwm5R8GURiLfdtXGpqM:-Kwnpd-Gi62BUoWzpYY2:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/a2a97139b9e2c78260cc1f0544b6517ee6370b63/vaadin-radio-group.html#L116)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Would it make sense not to require the radio buttons to be direct children and base types? Rather use `querySelectorAll('*')` and then filter the results by `instanceof Vaadin.RadioButtonElement`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16)*

**Comment by tomivirkki** [comment]
*[demo/radio-group-demos.html, line 64 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-Kwo6i300RGp121kF7ab:-Kwo6i300RGp121kF7ac:b-md7mym) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/adadd32cbe139513629bc4684b16bfc8d14bd0cc/demo/radio-group-demos.html#L64)):*
> ```HTML
>     </vaadin-demo-snippet>
> 
>     <h3>Radio Group with Iron Form with custom value</h3>
> ```

The element in this demo is invalid when you open the demo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16)*

**Comment by tomivirkki** [comment]
Review status: 0 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-radio-button.html, line 47 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-KwpnPy15HV5WseyOUE_:-KwpnPy15HV5WseyOUEa:b-8lz37f) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/4e58bd28ceec9e660726aaddb5062e47037824ad/vaadin-radio-button.html#L47)):*
> ```HTML
> <dom-module id="vaadin-radio-button">
>   <template>
>     <label part="wrapper" id="label" on-click="_preventDefault">
> ```

If possible, remove id's. Generic id names like "label" are just asking for trouble when running on shady. Can be done in a separate PR.

---

*[vaadin-radio-button.html, line 145 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-KwpmwR1iLEqyE8p86-7:-KwpmwR1iLEqyE8p86-8:b-mhblj9) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/4e58bd28ceec9e660726aaddb5062e47037824ad/vaadin-radio-button.html#L145)):*
> ```HTML
>           this.setAttribute('aria-checked', checked);
> 
>           this.dispatchEvent(new CustomEvent('change', {bubbles: true}));
> ```

`change` event should only be fired on user-action. Can be removed.

---

*[vaadin-radio-group.html, line 35 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-Kwph4bhv6rSKgOIqqtQ:-Kwph4biSg49LozyBJ7K:b-9vyxpu) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/4a250e6b8b2cada6e2338be1d143669860a8d7f6/vaadin-radio-group.html#L35)):*
> ```HTML
>        *
>        * ```html
>        * <vaadin-radio-button-group name="radio-group" value="bar">
> ```

Fix the example code here

---

*[vaadin-radio-group.html, line 176 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-KwpkdUKQOU-fDbgu-Wq:-KwpkdUKQOU-fDbgu-Wr:b3iyor5) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/4e58bd28ceec9e660726aaddb5062e47037824ad/vaadin-radio-group.html#L176)):*
> ```HTML
>         }
> 
>         _selectNextButton(element) {
> ```

If you disable the first button in the first demo, you can see this isn't working correctly. The disabled button is focusable with right arrow. Same issue happens in reverse if you disable the last button.

Also, if all buttons are disabled, you'll end up in an eternal loop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16)*

**Comment by Toshegg** [comment]
Review status: 0 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-radio-button.html, line 47 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-KwpnPy15HV5WseyOUE_:-Kwsd5xo_6NeqdzYuemq:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/4e58bd28ceec9e660726aaddb5062e47037824ad/vaadin-radio-button.html#L47)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

If possible, remove id's. Generic id names like "label" are just asking for trouble when running on shady. Can be done in a separate PR.
</blockquote></details>

Done.

---

*[vaadin-radio-button.html, line 145 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-KwpmwR1iLEqyE8p86-7:-Kwsd79bT5uGUWd-bOdY:bt1b19p) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/4e58bd28ceec9e660726aaddb5062e47037824ad/vaadin-radio-button.html#L145)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

`change` event should only be fired on user-action. Can be removed.
</blockquote></details>

Renamed.

---

*[vaadin-radio-group.html, line 35 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-Kwph4bhv6rSKgOIqqtQ:-KwsatZZ4pQjwSxrj4H1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/4a250e6b8b2cada6e2338be1d143669860a8d7f6/vaadin-radio-group.html#L35)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Fix the example code here
</blockquote></details>

Done.

---

*[demo/radio-group-demos.html, line 64 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-Kwo6i300RGp121kF7ab:-Kwsd2_JltrkNnZsTvT6:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/adadd32cbe139513629bc4684b16bfc8d14bd0cc/demo/radio-group-demos.html#L64)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The element in this demo is invalid when you open the demo
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16)*

**Comment by Toshegg** [comment]
Review status: 0 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-radio-group.html, line 176 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-KwpkdUKQOU-fDbgu-Wq:-KwsrwUyks0iY6eAgTNi:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/4e58bd28ceec9e660726aaddb5062e47037824ad/vaadin-radio-group.html#L176)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

If you disable the first button in the first demo, you can see this isn't working correctly. The disabled button is focusable with right arrow. Same issue happens in reverse if you disable the last button.

Also, if all buttons are disabled, you'll end up in an eternal loop.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16)*

**Comment by tomivirkki** [comment]
*[vaadin-radio-button.html, line 47 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-KwpnPy15HV5WseyOUE_:-KwtEgfwHfdZvLhQl3QV:b-7tz9t2) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/4e58bd28ceec9e660726aaddb5062e47037824ad/vaadin-radio-button.html#L47)):*
>  id="nativeRadio"
There is still at least one id

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16)*

**Comment by tomivirkki** [comment]
*[vaadin-radio-group.html, line 176 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-KwpkdUKQOU-fDbgu-Wq:-KwtFUgGOCXSZ8zKTSRu:b-mxxchr) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/4e58bd28ceec9e660726aaddb5062e47037824ad/vaadin-radio-group.html#L176)):*
<details><summary><i>Previously, Toshegg wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm still getting `Maximum call stack size exceeded` when all the buttons are disabled and arrows are hit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16)*

**Comment by Toshegg** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-radio-button.html, line 47 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-KwpnPy15HV5WseyOUE_:-KxC5L5GuArHJhaKYNdN:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/4e58bd28ceec9e660726aaddb5062e47037824ad/vaadin-radio-button.html#L47)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

>  id="nativeRadio"
There is still at least one id
</blockquote></details>

Done.

---

*[vaadin-radio-group.html, line 176 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-KwpkdUKQOU-fDbgu-Wq:-KxC5KZ0jvNB9W3GWhK-:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/4e58bd28ceec9e660726aaddb5062e47037824ad/vaadin-radio-group.html#L176)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I'm still getting `Maximum call stack size exceeded` when all the buttons are disabled and arrows are hit.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 6 of 14 files at r1, 3 of 9 files at r2, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-:-KxCIMw_JvD5jOKuCR15:bnfp4nl)*

**Comment by limonte** [comment]
Reviewed 6 of 14 files at r1, 3 of 9 files at r2, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[vaadin-radio-group.html, line 17 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-KxCU80YuyBPH-L3DC6A:-KxCU80YuyBPH-L3DC6B:b-qx6at4) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/4a250e6b8b2cada6e2338be1d143669860a8d7f6/vaadin-radio-group.html#L17)):*
> ```HTML
>       }
> 
>       :host([invalid]) {
> ```

Why removed? 

@tomivirkki What is the agreements on default styles for the `invalid` state? Should we include those into the default theme?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16)*

**Comment by Toshegg** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-radio-group.html, line 17 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-KxCU80YuyBPH-L3DC6A:-KxCYfHabIesP3IHmXNW:b6mygio) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/4a250e6b8b2cada6e2338be1d143669860a8d7f6/vaadin-radio-group.html#L17)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Why removed? 

@tomivirkki What is the agreements on default styles for the `invalid` state? Should we include those into the default theme?
</blockquote></details>

We've dropped required attribute from radio-group, so we needed to drop invalid state as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/16#-:-KxDGa2LElcnyQ5UWajC:bnfp4nl)*

**Pull request merged**
