### PR TITLE
Improved accessibility for screen readers, added disabled demo

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Improved accessibility for screen readers, added disabled demo, minor change to styles of vaadin-radio-button

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/3)

### CODE REVIEW

**Comment by platosha** [comment]
It is now possible to toggle disabled radio buttons by clicking the label. Also applies to disabled radio group.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/3#-:-KoS5eJ0KhmA-P4nNhyG:b-n0kpq0)*

**Comment by YuriyVaadin** [comment]
Fixed in https://github.com/vaadin/vaadin-radio-button/pull/3/commits/ad8acbc857b9a895fe003d60a9a34536de8dd4ef

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/3#-:-KoSXBBrQszlmkbNb55X:bn2v8ku)*

**Comment by platosha** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-radio-button.html, line 124 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/3#-KofiVAstbMifFMZqIvp:-KofiVAstbMifFMZqIvq:b-j218js) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/ad8acbc857b9a895fe003d60a9a34536de8dd4ef/vaadin-radio-button.html#L124)):*
> ```HTML
>              * The current disabled state of the radio button. True if disabled.
>              */
>             disabled: {
> ```

I wonder if we should set `aria-disabled="true"` on the radio button as well when disabled.

At least with VoiceOver having `aria-disabled` makes a difference: it says “dimmed” when navigating with VoiceOver cursor, it says “dimmed” as feedback when user interacts with the radio button.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/3)*

**Comment by platosha** [comment]
OK toggling works as expected now.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/3#-:-KofjWztKqOtu32_lVvD:b-2ciug0)*

**Comment by YuriyVaadin** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-radio-button.html, line 124 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/3#-KofiVAstbMifFMZqIvp:-Kog-juQNH__4JW0Y20X:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/ad8acbc857b9a895fe003d60a9a34536de8dd4ef/vaadin-radio-button.html#L124)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

I wonder if we should set `aria-disabled="true"` on the radio button as well when disabled.

At least with VoiceOver having `aria-disabled` makes a difference: it says “dimmed” when navigating with VoiceOver cursor, it says “dimmed” as feedback when user interacts with the radio button.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/3)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-radio-button-group.html, line 149 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/3#-Kog0tPtqbKsQ5K7ldxd:-Kog0tPtqbKsQ5K7ldxe:b-qicqu7) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/988c5aac9d8df7bb6d0bd3f6cf6a6d9af6b4ad41/vaadin-radio-button-group.html#L149)):*
> ```HTML
>           this._forEachButton(button => button.disabled = disabled);
> 
>           this._forEachButton(button => button.setAttribute('aria-disabled', disabled));
> ```

This is not helpful for cases when one or several radio buttons are disabled inside of non-disabled group. Consider:

```html
<vaadin-radio-button-group name="option">
  <vaadin-radio-button disabled>One</vaadin-radio-button>
  <vaadin-radio-button>Two</vaadin-radio-button>
  <vaadin-radio-button>Three</vaadin-radio-button>
</vaadin-radio-button>
```

Instead, I would rather implement this in a disabled property observer in the radio button.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/3)*

**Comment by YuriyVaadin** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-radio-button-group.html, line 149 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/3#-Kog0tPtqbKsQ5K7ldxd:-Kog3UZYToRnVPwGjqR1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/988c5aac9d8df7bb6d0bd3f6cf6a6d9af6b4ad41/vaadin-radio-button-group.html#L149)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

This is not helpful for cases when one or several radio buttons are disabled inside of non-disabled group. Consider:

```html
<vaadin-radio-button-group name="option">
  <vaadin-radio-button disabled>One</vaadin-radio-button>
  <vaadin-radio-button>Two</vaadin-radio-button>
  <vaadin-radio-button>Three</vaadin-radio-button>
</vaadin-radio-button>
```

Instead, I would rather implement this in a disabled property observer in the radio button.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/3)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/3#-:-KogD9iKdvW9Rs1RTWuu:bnfp4nl)*

**Pull request merged**
