### PR TITLE
Dirty fix for name documentation

### PR DESCRIPTION
**Pull request by Toshegg**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/20)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-radio-button.html, line 143 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/20#-KxReO3ZKI6ftJdb3oc3:-KxReO3ZKI6ftJdb3oc4:b-pf2xf8) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/bfb7db091f5d1a600b7088e54c7c7d2e0695d297/vaadin-radio-button.html#L143)):*
> ```HTML
>         }
> 
>         _checkedNameObserver(checked, name) {
> ```

Could the logic be simplified to following?
```
if (name) {
  this._storedName = name;
}
this.name = this.checked ? this._storedName : '';
```
At least all the tests pass

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/20)*

**Comment by Toshegg** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-radio-button.html, line 143 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/20#-KxReO3ZKI6ftJdb3oc3:-KxRlp_7K1ZV7duyxQPQ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/bfb7db091f5d1a600b7088e54c7c7d2e0695d297/vaadin-radio-button.html#L143)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Could the logic be simplified to following?
```
if (name) {
  this._storedName = name;
}
this.name = this.checked ? this._storedName : '';
```
At least all the tests pass
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/20)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/20#-:-KxRr2rjpRJ3tacTEf2a:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/20)*

**Pull request merged**
