### PR TITLE
Fix issue where safari 9 focuses input inside vaadin-radio-button

### PR DESCRIPTION
**Pull request by samiheikki**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/44)

### CODE REVIEW

**Comment by web-padawan** [comment]
I have tried this with iOS 9.3 simulator and the fix looks good (all test tests passing), just a few nits.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[analysis.json, line 1164 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/44#-L5hm_Lgf5G3bQfaDNWW:-L5hm_Lgf5G3bQfaDNWX:bzf3c8n) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/95b8b15944817b59290fde785ed4ef8bf0a4c7cd/analysis.json#L1164)):*
> ```JSON
>     }
>   ],
>   "elements": [
> ```

Please either revert this change, since we are going to bump before cutting next beta release, or do it in a proper way so that `analysis.json` do not include demo elements.

---

*[src/vaadin-radio-group.html, line 165 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/44#-L5hnPKm5ViZZ3wjgdeS:-L5hnPKm5ViZZ3wjgdeT:b-423p76) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/95b8b15944817b59290fde785ed4ef8bf0a4c7cd/src/vaadin-radio-group.html#L165)):*
> ```HTML
>             // Safari 9 focuses the <input> inside <vaadin-radio-button>
>             // Check if the focus is inside <vaadin-radio-button>'s
>             const focusedElements = Array.from(this.querySelectorAll('vaadin-radio-button')).filter(el => {
> ```

nit: consider using `some` instead of `filter` and checking `length` so that would become a one-liner.

---

*[src/vaadin-radio-group.html, line 166 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/44#-L5hmzduRUuDEen4z57X:-L5hmzduRUuDEen4z57Y:b-u3bd72) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/95b8b15944817b59290fde785ed4ef8bf0a4c7cd/src/vaadin-radio-group.html#L166)):*
> ```HTML
>             // Check if the focus is inside <vaadin-radio-button>'s
>             const focusedElements = Array.from(this.querySelectorAll('vaadin-radio-button')).filter(el => {
>               return el.shadowRoot.contains(this.getRootNode().activeElement);
> ```

nit: consider saving the reference to the active element once:
```
const activeElement = this.getRootNode().activeElement;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/44#-:-L5hnexh_uzJ6xkVO92C:biu6kx0)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/vaadin-radio-group.html, line 165 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/44#-L5hnPKm5ViZZ3wjgdeS:-L5moTUPOQ3CR-iBrGD1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/95b8b15944817b59290fde785ed4ef8bf0a4c7cd/src/vaadin-radio-group.html#L165)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: consider using `some` instead of `filter` and checking `length` so that would become a one-liner.
</blockquote></details>

Done.

---

*[src/vaadin-radio-group.html, line 166 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/44#-L5hmzduRUuDEen4z57X:-L5moUG7Y8RG76RVASkI:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/95b8b15944817b59290fde785ed4ef8bf0a4c7cd/src/vaadin-radio-group.html#L166)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: consider saving the reference to the active element once:
```
const activeElement = this.getRootNode().activeElement;
```
</blockquote></details>

Done.

---

*[analysis.json, line 1164 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/44#-L5hm_Lgf5G3bQfaDNWW:-L5moVG9Bi39Ypn6-HLy:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/95b8b15944817b59290fde785ed4ef8bf0a4c7cd/analysis.json#L1164)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Please either revert this change, since we are going to bump before cutting next beta release, or do it in a proper way so that `analysis.json` do not include demo elements.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/44)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/44#-:-L5mp0WORxWG1z1mkv8B:bnfp4nl)*

**Comment by samiheikki** [comment]
:lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/44#-:-L5nYEfpjX_29kI3xRHh:bg7igkv)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/vaadin-radio-group.html, line 164 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/44#-L5nbhQWD_PRvcszOTTu:-L5nbhQWD_PRvcszOTTv:bj74i34) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/18701e5a488ef2f70f2cee4585229dbe00414e4f/src/vaadin-radio-group.html#L164)):*
> ```HTML
>             return true;
>           } else {
>             // Safari 9 focuses the <input> inside <vaadin-radio-button>
> ```

BTW the comment does not entirely explain the issue to me.

`activeElement` is polyfilled in ShadyDOM to not leak nodes from shadow roots and return the host instead.

Even when the actual focused element is an input from the `<vaadin-radio-button>`’s shadow root, I would expect the `activeElement` from the parent scope to point to the radio button’s host...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/44)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/vaadin-radio-group.html, line 164 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/44#-L5nbhQWD_PRvcszOTTu:-L5ndV-dPbJfrXgESeNo:br9xta3) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/18701e5a488ef2f70f2cee4585229dbe00414e4f/src/vaadin-radio-group.html#L164)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW the comment does not entirely explain the issue to me.

`activeElement` is polyfilled in ShadyDOM to not leak nodes from shadow roots and return the host instead.

Even when the actual focused element is an input from the `<vaadin-radio-button>`’s shadow root, I would expect the `activeElement` from the parent scope to point to the radio button’s host...
</blockquote></details>

BTW not a blocker, just wondering here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/44)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-radio-group.html, line 164 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/44#-L5nbhQWD_PRvcszOTTu:-L5oXPUA2R-BI2glgnzo:bcf0i4f) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/18701e5a488ef2f70f2cee4585229dbe00414e4f/src/vaadin-radio-group.html#L164)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW not a blocker, just wondering here
</blockquote></details>

So after some investigation I discovered that we have to use `_activeElement` here because of missing builtin accessors in Safari 9. See the comments about this [here](https://github.com/webcomponents/shadydom/blob/2e4b73247a2bf413148acb2970f2a0dea886c837/src/patch-accessors.js#L389) and [here](https://github.com/webcomponents/shadydom/blob/006b3d651acf0df1d04e5442a89c55dcd70e94ea/src/patch-builtins.js#L296), and the actual implementation for legacy `Polymer.dom` [here](https://github.com/Polymer/polymer/blob/2e39cf6f6b16f26db869fb13cce9761d8871c479/lib/legacy/polymer.dom.html#L194).

In this particular case, `_activeElement` returns `vaadin-radio-button` like it should. I tried this in simulator and tests are passing. Updated the PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/44)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/44)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/44)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/44#-:-L5rZ1Z2HSQo_Aojbgm0:bnfp4nl)*

**Pull request merged**
