### PR TITLE
Do not steal focus from the current component when changing value programmatically

### LINKED ISSUE #23: Radio group steals focus on value change.
If you programmatically change the value of a group it will steal the focus away from whatever component initially had focus.

### PR DESCRIPTION
**Pull request by vicsstar**
Fixes #23

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/24)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Test case needed

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-radio-group.html, line 163 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/24#-Ky1QEb0Y-4pcLxs3q2R:-Ky1QEb1-PlYfyVsjJXX:b1iuo3s) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/3ea99cb8c041b1115d549a0dd863b7a475208c73/vaadin-radio-group.html#L163)):*
> ```HTML
> 
>         _selectButton(element) {
>           element.focus();
> ```

This invalidates keyboard navigation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/24#-:-Ky1QGr_W8pAxaZhFarp:b-u6b550)*

**Comment by vicsstar** [comment]
@limonte didn't quite catch that; what's the PR description?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/24#-:-KyGMZPcqMM_uqgv67bZ:bjhe6h2)*

**Comment by limonte** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/vaadin-radio-group.html, line 161 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/24#-KyGc6yxeNfyv811sRdR:-KyGc6yxeNfyv811sRdS:b-dnp4a1) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/0a5920d20245cb22807bbe2a172fcb545932ac9e/test/vaadin-radio-group.html#L161)):*
> ```HTML
>       });
> 
>       it('should NOT steal focus from currently focused component', () => {
> ```

`focused component` -> `focused element`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/24)*

**Comment by vicsstar** [comment]
*[vaadin-radio-group.html, line 163 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/24#-Ky1QEb0Y-4pcLxs3q2R:-KyGeAJEIXoEuS8OVp8f:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/3ea99cb8c041b1115d549a0dd863b7a475208c73/vaadin-radio-group.html#L163)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This invalidates keyboard navigation
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/24)*

**Comment by vicsstar** [comment]
*[test/vaadin-radio-group.html, line 161 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/24#-KyGc6yxeNfyv811sRdR:-KyGeX6u89fggavKbEvG:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/0a5920d20245cb22807bbe2a172fcb545932ac9e/test/vaadin-radio-group.html#L161)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

`focused component` -> `focused element`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/24)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/24#-:-KyGeyQ9gesGFDGvshOo:bnfp4nl)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/24#-:-KyGh_jdOv6EeeCf-y10:bnfp4nl)*

**Pull request merged**
