### PR TITLE
Preserve focus-ring attribute when navigating with arrow keys

### LINKED ISSUE #39: Focus-ring is lost when using keyboard navigation inside radio-group
The focus-ring style is visible when moving the focus to the radio group with the tab key, but is removed when the user navigates the options with arrow keys.

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #39

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/42)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-radio-group.html, line 156 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42#-L3T4WCQJHNnyK9_rAuR:-L3T4WCQJHNnyK9_rAuS:b-6q5xg1) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/d265edafdb67747718286b1bd996b866e0584fa1/src/vaadin-radio-group.html#L156)):*
> ```HTML
>             if (this._arrowKeyPressed) {
>               element.setAttribute('focus-ring', '');
>               delete this._arrowKeyPressed;
> ```

I would prefer to set `this._arrowKeyPressed = false`. 
Not a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42#-:-L3T4gBncwdzElxxtzGV:bnfp4nl)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-radio-group.html, line 138 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42#-L3X942FvQANaurhiAZd:-L3X9QNEsLX98F-qqtmU:b-8qrif8) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/d265edafdb67747718286b1bd996b866e0584fa1/src/vaadin-radio-group.html#L138)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Could we use an argument rather than a flag in this case?

Explicit args should be preferred over implicit flags IMO.
</blockquote></details>

Hint: please mention focus ring in the argument name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42)*

**Comment by web-padawan** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-radio-group.html, line 138 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42#-L3X942FvQANaurhiAZd:-L3XExOOIZmvqf9_f0KL:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/d265edafdb67747718286b1bd996b866e0584fa1/src/vaadin-radio-group.html#L138)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Hint: please mention focus ring in the argument name.
</blockquote></details>

Done.

---

*[src/vaadin-radio-group.html, line 156 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42#-L3T4WCQJHNnyK9_rAuR:-L3XF2fU1VwG7Qdkzjhg:btv45rj) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/d265edafdb67747718286b1bd996b866e0584fa1/src/vaadin-radio-group.html#L156)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

I would prefer to set `this._arrowKeyPressed = false`. 
Not a blocker.
</blockquote></details>

Removed this flag at all. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42)*

**Comment by platosha** [comment]
Review status: 1 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/vaadin-radio-group.html, line 138 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42#-L3XJ5_NIlyr0lgEEchC:-L3XJ5_NIlyr0lgEEchD:b-kaoav5) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/c61f0061af3a1d49c430c95e08a4da50f0619e42/src/vaadin-radio-group.html#L138)):*
> ```HTML
>             if (e.keyCode === 37 || e.keyCode === 38) {
>               e.preventDefault();
>               this._arrowKeyPressed = true;
> ```

No need to set the flag anymore.

---

*[src/vaadin-radio-group.html, line 145 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42#-L3XJEDdQoBmUafSqMWp:-L3XJEDdQoBmUafSqMWq:brhumzt) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/c61f0061af3a1d49c430c95e08a4da50f0619e42/src/vaadin-radio-group.html#L145)):*
> ```HTML
>             if (e.keyCode === 39 || e.keyCode === 40) {
>               e.preventDefault();
>               this._arrowKeyPressed = true;
> ```

Same here.

---

*[src/vaadin-radio-group.html, line 173 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42#-L3XJUWYlXcoANzAcDYo:-L3XJUWYlXcoANzAcDYp:bb2lz) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/c61f0061af3a1d49c430c95e08a4da50f0619e42/src/vaadin-radio-group.html#L173)):*
> ```HTML
> 
>           if (nextButton.disabled) {
>             this._selectNextButton(nextButton, true);
> ```

I suppose this should pass `moveFocusRing`, but not always `true`.

Alternatively, considering that `_selectNextButton` and `_selectPreviousButton` are only called for keyboard arrow keys, you could remove `_selectNextButton` arguments and pass `true` to `_selectButton` directly, when called in `_selectNextButton` or `_selectPreviousButton`.

---

*[src/vaadin-radio-group.html, line 175 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42#-L3XJaB5fSPan2L9riv2:-L3XJaB5fSPan2L9riv3:brhumzt) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/c61f0061af3a1d49c430c95e08a4da50f0619e42/src/vaadin-radio-group.html#L175)):*
> ```HTML
>             this._selectNextButton(nextButton, true);
>           } else {
>             this._selectButton(nextButton, true);
> ```

Same here.

---

*[src/vaadin-radio-group.html, line 187 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42#-L3XJcuOqSVvNVStIT2j:-L3XJcuOqSVvNVStIT2k:brhumzt) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/c61f0061af3a1d49c430c95e08a4da50f0619e42/src/vaadin-radio-group.html#L187)):*
> ```HTML
> 
>           if (previousButton.disabled) {
>             this._selectPreviousButton(previousButton, true);
> ```

Same here.

---

*[src/vaadin-radio-group.html, line 189 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42#-L3XJdh7PlXPUpZo0B_G:-L3XJdh7PlXPUpZo0B_H:brhumzt) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/c61f0061af3a1d49c430c95e08a4da50f0619e42/src/vaadin-radio-group.html#L189)):*
> ```HTML
>             this._selectPreviousButton(previousButton, true);
>           } else {
>             this._selectButton(previousButton, true);
> ```

Same here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42)*

**Comment by platosha** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42)*

**Comment by web-padawan** [comment]
Review status: 1 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/vaadin-radio-group.html, line 138 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42#-L3XJ5_NIlyr0lgEEchC:-L3XLdBheR6Zu-QfjPiO:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/c61f0061af3a1d49c430c95e08a4da50f0619e42/src/vaadin-radio-group.html#L138)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

No need to set the flag anymore.
</blockquote></details>

Done.

---

*[src/vaadin-radio-group.html, line 145 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42#-L3XJEDdQoBmUafSqMWp:-L3XLdV14s4RzKUM5wkl:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/c61f0061af3a1d49c430c95e08a4da50f0619e42/src/vaadin-radio-group.html#L145)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

---

*[src/vaadin-radio-group.html, line 173 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42#-L3XJUWYlXcoANzAcDYo:-L3XM1BM-hm14AJVgnCQ:b-l05v9g) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/c61f0061af3a1d49c430c95e08a4da50f0619e42/src/vaadin-radio-group.html#L173)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

I suppose this should pass `moveFocusRing`, but not always `true`.

Alternatively, considering that `_selectNextButton` and `_selectPreviousButton` are only called for keyboard arrow keys, you could remove `_selectNextButton` arguments and pass `true` to `_selectButton` directly, when called in `_selectNextButton` or `_selectPreviousButton`.
</blockquote></details>

Implemented the second suggestion. Done.

---

*[src/vaadin-radio-group.html, line 175 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42#-L3XJaB5fSPan2L9riv2:-L3XM1Xro2Wb06aCQV0P:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/c61f0061af3a1d49c430c95e08a4da50f0619e42/src/vaadin-radio-group.html#L175)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

---

*[src/vaadin-radio-group.html, line 187 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42#-L3XJcuOqSVvNVStIT2j:-L3XM1wfnybsCsmuKWc8:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/c61f0061af3a1d49c430c95e08a4da50f0619e42/src/vaadin-radio-group.html#L187)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

---

*[src/vaadin-radio-group.html, line 189 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42#-L3XJdh7PlXPUpZo0B_G:-L3XM2FvikQC5GAl0DWX:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/c61f0061af3a1d49c430c95e08a4da50f0619e42/src/vaadin-radio-group.html#L189)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/42#-:-L3XVnlpnLm6Uhaz12Uq:bnfp4nl)*

**Pull request merged**
