### PR TITLE
Added label property to the vaadin-radio-group

### PR DESCRIPTION
**Pull request by gatanaso**
Connected to #19 

This PR introduces a `label`property to the `<vaadin-radio-group>` element.

screen shot 2018-05-18 at 16 09 49

The label is styled according to the same rules used for other vaadin component labels.

This PR does not introduce the styles for `required` or `error` states of the component, since those are not yet available as properties.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)

### CODE REVIEW

**Comment by jouni** [comment]
Not really a fault of this PR, but it just highlights the problem that we have with styling, that there’s no good way to share styles between components.

As a future enhancement, to keep it DRY, I suppose the best we could do is extract the label styles into a new style module in `vaadin-lumo-styles`, using the `[part="label"]` selector.

@platosha, thoughts?

**Comment by tomivirkki** [comment]
*[src/vaadin-radio-group.html, line 21 at r1](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-LCnV9_WAGLI1a0-W4qe:-LCnV9_WAGLI1a0-W4qf:bjr39cx) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/614aa35214385c5e3b2584b0993bba6bd4726575/src/vaadin-radio-group.html#L21)):*
> ```HTML
>       :host([has-label])::before {
>         /* Label height + margin */
>         margin-top: calc(var(--lumo-font-size-s) * 1.5);
> ```

Lumo-specific stuff should be moved under themes/lumo/

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/radio-group-demos.html, line 35 at r2](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-LD0_m5oEMmbmknGKv_e:-LD0_m5oEMmbmknGKv_f:b-jexpi7) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/aca4ae48691e4cbcfb10da49ccacf28d9979e5e1/demo/radio-group-demos.html#L35)):*
> ```HTML
>     <vaadin-demo-snippet id="radio-group-demos-radio-group-label">
>       <template preserve-content>
>         <vaadin-radio-group label="Radio Group">
> ```

Do you mind to use a real use case here, lately we try not to use meaningless examples

---

*[src/vaadin-radio-group.html, line 261 at r2](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-LD0ZzgB7nv4s-BcYegr:-LD0ZzgB7nv4s-BcYegs:b4pkx5e) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/aca4ae48691e4cbcfb10da49ccacf28d9979e5e1/src/vaadin-radio-group.html#L261)):*
> ```HTML
> 
>         _labelChanged(label) {
>           if (label !== '' && label != null) {
> ```

I think here you can safely use `if (label)` 

---

*[test/vaadin-radio-group.html, line 213 at r2](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-LD0YbyPAjx73c2bp4Gp:-LD0YbyQ3mx2Oz95DHPs:bqdb7o8) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/aca4ae48691e4cbcfb10da49ccacf28d9979e5e1/test/vaadin-radio-group.html#L213)):*
> ```HTML
>         vaadinRadioButtonGroup.label = 'foo';
> 
>         expect(vaadinRadioButtonGroup.hasAttribute('has-label')).to.be.true;
> ```

It's better assertion check that label has the actual value of 'foo' 

---

*[theme/lumo/vaadin-radio-group.html, line 12 at r2](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-LD0bIPP8g4AJ0Ehfpsg:-LD0bIPP8g4AJ0Ehfpsh:bcb563i) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/aca4ae48691e4cbcfb10da49ccacf28d9979e5e1/theme/lumo/vaadin-radio-group.html#L12)):*
> ```HTML
> 
>       :host([has-label])::before {
>         /* Label height + margin */
> ```

You copied this from text-field, but I think the comment is not needed

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-:-LD3UraTBP8M-CG9kPy7:bnfp4nl)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-radio-group.html, line 88 at r3](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-LD5c-zh6J4f0XGQ5nW_:-LD5c-zh6J4f0XGQ5nWa:b-figxiu) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/ca15cf2f03d2177b7bed307ef7c3a26d6ad0d22a/src/vaadin-radio-group.html#L88)):*
> ```HTML
> 
>             /**
>             * String used for the label element.
> ```

BTW misaligned JSDoc comment, one more whitespace in this line and below.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by web-padawan** [comment]
Reviewed 3 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4, 2 of 3 files at r5, 7 of 7 files at r6.
Review status: all files reviewed, 1 unresolved discussion (waiting on @gatanaso)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-:-LFrU1hFE5uvSZp3pRtC:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-LFwWG-P9fl-QhIcAaup:-LFwWG-P9fl-QhIcAauq:b-d73axt) (no related file):*
Baseline seems off with both of the themes:
https://www.dropbox.com/s/6uzq24y8sdi8bem/Screenshot%202018-06-26%2017.33.09.png?dl=0
https://www.dropbox.com/s/mpg93y2t96v7wvw/Screenshot%202018-06-26%2017.40.38.png?dl=0

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by manolo** [comment]
@tomivirkki  foobar demo 

---

Reviewed 1 of 1 files at r7, 1 of 1 files at r9.
Review status: all files reviewed, 3 unresolved discussions (waiting on @gatanaso)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-:-LFwn55D-ULxBktOsISn:b-j8mpdm)*

**Comment by tomivirkki** [comment]
@manolo What about it? My commit removed the foobar demo.

---







*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-:-LFwoL36584tJTGPFYLY:b-r2n3li)*

**Comment by manolo** [comment]
Reviewed 2 of 2 files at r10.
Review status: all files reviewed, 3 unresolved discussions (waiting on @gatanaso)

---

*[src/vaadin-radio-group.html, line 21 at r1](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-LCnV9_WAGLI1a0-W4qe:-LFwo_y5CtDEiBExiVqq:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/614aa35214385c5e3b2584b0993bba6bd4726575/src/vaadin-radio-group.html#L21)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Lumo-specific stuff should be moved under themes/lumo/
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by manolo** [comment]
We did the same thing. Restored in your way and squashed my commits.

---

Reviewed 2 of 2 files at r11.
Review status: all files reviewed, 3 unresolved discussions (waiting on @tomivirkki and @gatanaso)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-:-LFwqbB19XdM1BuAvweB:b-r2voo9)*

**Comment by manolo** [comment]
Review status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @manolo, @tomivirkki, and @gatanaso)

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-LFwWG-P9fl-QhIcAaup:-LFwr1_OBYLImu1aAl-Q:b-bbk615) (no related file):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Baseline seems off with both of the themes:
https://www.dropbox.com/s/6uzq24y8sdi8bem/Screenshot%202018-06-26%2017.33.09.png?dl=0
https://www.dropbox.com/s/mpg93y2t96v7wvw/Screenshot%202018-06-26%2017.40.38.png?dl=0
</blockquote></details>

I see them aligned:

http://g.recordit.co/wIp3kpQTvs.gif
http://g.recordit.co/ppVzbDreWv.gif

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by manolo** [comment]
Review status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @manolo, @tomivirkki, and @gatanaso)

---

*[theme/material/vaadin-radio-group-styles.html, line 26 at r7](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-LFwTtfS-lJAdNWYD7d4:-LFwyvq76FZBDusWFFM6:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/260481e244255dbf8a07d3d0dc7490d4f963631c/theme/material/vaadin-radio-group-styles.html#L26)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

These transition properties are not used for anything since the label doesn't float
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r12.
Review status: all files reviewed, 3 unresolved discussions (waiting on @tomivirkki)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by YuriyVaadin** [comment]
Reviewed 1 of 3 files at r5, 1 of 7 files at r6, 1 of 2 files at r10, 2 of 2 files at r11, 1 of 1 files at r12, 5 of 5 files at r13.
Review status: all files reviewed, 3 unresolved discussions (waiting on @tomivirkki)

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-LFwWG-P9fl-QhIcAaup:-LG-57Pa61Zngy8AHf1J:b-j9dxc4) (no related file):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I see them aligned:

http://g.recordit.co/wIp3kpQTvs.gif
http://g.recordit.co/ppVzbDreWv.gif


</blockquote></details>

Seems to be ok.
https://www.dropbox.com/s/g3yugv07v2m1uw8/Screen%20Shot%202018-06-27%20at%2010.18.41.png?dl=0
https://www.dropbox.com/s/irs14nwtrol4je2/Screen%20Shot%202018-06-27%20at%2010.19.02.png?dl=0

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by YuriyVaadin** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @tomivirkki and @manolo)

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-LFwWG-P9fl-QhIcAaup:-LG-mLiS94M8o1qQ38lf:bvzrufj) (no related file):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

@yuriyvaadin your screenshots don't have the components wrapped in a flexbox
</blockquote></details>

Yeah, sorry. Just checked. The baseline is misaligned.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by manolo** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @tomivirkki)

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-LFwWG-P9fl-QhIcAaup:-LG-rYqv6scT9Nxo8Rsl:b-dc0ax4) (no related file):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Yeah, sorry. Just checked. The baseline is misaligned.
</blockquote></details>

I took a look to text-field and seems that covering baseline in a flex context needs much more work, basically some wrappers and styles for those.

I'll try to figure out all the changes needed for that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by tomivirkki** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-LG45mk29g0oiEsn9hhk:-LG45mk29g0oiEsn9hhl:b-cykkzd) (no related file):*
New API needs an update to analysis.json

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by manolo** [comment]
Reviewed 8 of 8 files at r14.
Review status: all files reviewed, 4 unresolved discussions (waiting on @tomivirkki and @gatanaso)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by manolo** [comment]
Reviewed 1 of 2 files at r15.
Review status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @manolo, @tomivirkki, and @gatanaso)

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-LG45mk29g0oiEsn9hhk:-LG4FjbmEcDhfF9fXMjd:bb6un1j) (no related file):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

New API needs an update to analysis.json
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by manolo** [comment]
Reviewed 1 of 2 files at r15.
Review status: all files reviewed, 4 unresolved discussions (waiting on @tomivirkki)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r14, 2 of 2 files at r16.
Review status: all files reviewed, 4 unresolved discussions (waiting on @tomivirkki)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-:-LG4WcDp-ABdpGZxBQXu:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r5, 1 of 7 files at r6, 1 of 2 files at r11, 7 of 8 files at r14, 2 of 2 files at r16.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-:-LG5_zEV35TuxWkSFUFD:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[theme/lumo/vaadin-radio-group-styles.html, line 5 at r16](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-LG5gG0s4S8y9-mNfWGm:-LG5gG0s4S8y9-mNfWGn:b-qyro4) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/f2dbbb8566f373e4678e1c7dc0cb6beae9049927/theme/lumo/vaadin-radio-group-styles.html#L5)):*
> ```HTML
>     <style>
>       :host {
>         --lumo-text-field-size: var(--lumo-size-m);
> ```

Shouldn't say text-field

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by manolo** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @tomivirkki)

---

*[theme/lumo/vaadin-radio-group-styles.html, line 5 at r16](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-LG5gG0s4S8y9-mNfWGm:-LG9KUi3AMhe65XmMhxw:bohybj5) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/f2dbbb8566f373e4678e1c7dc0cb6beae9049927/theme/lumo/vaadin-radio-group-styles.html#L5)):*
<details><summary><i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary><blockquote>

Where is this even used? The whole concept of component-specific​ size properties in Lumo is not fully​ thought out, and I would avoid adding any more of these (IIRC text-field and button have them).
</blockquote></details>

 @tomivirkki  It's used in `:host::before {height: var(--lumo-text-field-size);}` not sure if it's really needed and does not break anything.
 I mean if someone changes that value in global scope, and we have in `:host::before { height: var(--lumo-size-m));} ` are we going to have alignment problems @jouni ? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by manolo** [comment]
Review status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @YuriyVaadin, @manolo, and @tomivirkki)

---

*[theme/lumo/vaadin-radio-group-styles.html, line 5 at r16](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-LG5gG0s4S8y9-mNfWGm:-LG9RfwZ9EL7wwpYK69u:bxa13g9) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/f2dbbb8566f373e4678e1c7dc0cb6beae9049927/theme/lumo/vaadin-radio-group-styles.html#L5)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

 @tomivirkki  It's used in `:host::before {height: var(--lumo-text-field-size);}` not sure if it's really needed and does not break anything.
 I mean if someone changes that value in global scope, and we have in `:host::before { height: var(--lumo-size-m));} ` are we going to have alignment problems @jouni ? 
</blockquote></details>

Removed, setting value to `--lumo-size.m` 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by tomivirkki** [comment]
*[theme/lumo/vaadin-radio-group-styles.html, line 5 at r16](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62#-LG5gG0s4S8y9-mNfWGm:-LG9_87c9fSpwjoqtMMe:b-3y7lx0) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/f2dbbb8566f373e4678e1c7dc0cb6beae9049927/theme/lumo/vaadin-radio-group-styles.html#L5)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Removed, setting value to `--lumo-size.m` 
</blockquote></details>

What I meant was that the name of the property should have been "--lumo-radio-group-size" instead of "--lumo-text-field-size". But if it's not needed, even better.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r17.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/62)*

**Pull request merged**
