### PR TITLE
Add vaadin-radio-group value demo

### LINKED ISSUE #29: DX: Add a demo that uses the value property

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #29

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/30)

### CODE REVIEW

**Comment by limonte** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/radio-group-demos.html, line 38 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/30#-KyGD3QmdCxgwnwLP_SQ:-KyGD3QmdCxgwnwLP_SR:bgd20nb) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/6c775ec4022df3940cf3ec2c1e2c33059e60d6f7/demo/radio-group-demos.html#L38)):*
> ```HTML
>           <template>
>             <vaadin-radio-group value="{{radioValue}}">
>               <vaadin-radio-button value="foo">Foo</vaadin-radio-button>
> ```

It would be nicer to get rid of `foo-bar-baz` and replace those with some real-life example, e.g. 

How often would you like to receive notifications: 
 - daily
 - once a week
 - once a month

Related reading: https://uxplanet.org/common-ux-mistakes-that-can-kill-your-project-ccae026605ae

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/30)*

**Comment by Toshegg** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/30#-:-KyGJ-kEdApIkwOk262w:bnfp4nl)*

**Comment by web-padawan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/radio-group-demos.html, line 38 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/30#-KyGD3QmdCxgwnwLP_SQ:-KyGJ0lohb9FgDP6o1Pn:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/6c775ec4022df3940cf3ec2c1e2c33059e60d6f7/demo/radio-group-demos.html#L38)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

It would be nicer to get rid of `foo-bar-baz` and replace those with some real-life example, e.g. 

How often would you like to receive notifications: 
 - daily
 - once a week
 - once a month

Related reading: https://uxplanet.org/common-ux-mistakes-that-can-kill-your-project-ccae026605ae
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/30)*

**Comment by limonte** [comment]
much better now! :lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/30#-:-KyGJE0_xDJCmseAd_HB:bmvn3of)*

**Pull request merged**
