### PR TITLE
Validation api

### PR DESCRIPTION
**Pull request by manolo**
Connects to https://github.com/vaadin/vaadin-radio-button/issues/18

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
Reviewed 12 of 12 files at r1, 2 of 3 files at r2.
Review status: all files reviewed, 4 unresolved discussions (waiting on @manolo)

---

*[src/vaadin-radio-group.html, line 188 at r1](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67#-LG4W2378HbE1PymJBFn:-LG4W2378HbE1PymJBFo:byagp9j) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/bd5014d79598ad43f421c140907cfcf67326a4d0/src/vaadin-radio-group.html#L188)):*
> ```HTML
>               // it's not possible to set readonly to radio buttons, but we can
>               // unchecked ones instead.
>               button.disabled = button !== this._checkedButton && this.readonly;
> ```

This functionality of `readonly` state seems unusual to me. Do we really need to implement it? There is no such functionality in `paper-radio-group` or on MDN specification for `radiogroup`: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/radiogroup .

---

*[src/vaadin-radio-group.html, line 202 at r1](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67#-LG4VXHQEsy2lNSSLvAG:-LG4VXHQEsy2lNSSLvAH:b-jllpyz) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/bd5014d79598ad43f421c140907cfcf67326a4d0/src/vaadin-radio-group.html#L202)):*
> ```HTML
>           this.addEventListener('keydown', e => {
> 
>             if (this.disabled || this.readonly) {
> ```

Nit: untested code.

---

*[src/vaadin-radio-group.html, line 281 at r1](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67#-LG4VgjQ8pc0KotV-SvI:-LG4VgjQ8pc0KotV-SvJ:b-jllpyz) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/bd5014d79598ad43f421c140907cfcf67326a4d0/src/vaadin-radio-group.html#L281)):*
> ```HTML
>           this._radioButtons.forEach(button => button.checked = button === checkedButton);
>           this.value = checkedButton.value;
>           this.validate();
> ```

Nit: untested code.

---

*[src/vaadin-radio-group.html, line 295 at r1](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67#-LG4Vpg_1c19i1cz-IjO:-LG4Vpg_1c19i1cz-IjP:b-jllpyz) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/bd5014d79598ad43f421c140907cfcf67326a4d0/src/vaadin-radio-group.html#L295)):*
> ```HTML
>           }
> 
>           if (newV !== '' && newV != null) {
> ```

Nit: untested code.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67)*

**Comment by manolo** [comment]
Review status: all files reviewed, 4 unresolved discussions (waiting on @manolo)

---

*[src/vaadin-radio-group.html, line 188 at r1](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67#-LG4W2378HbE1PymJBFn:-LG4XZEg-haBH9ov7Hss:b-bmd11f) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/bd5014d79598ad43f421c140907cfcf67326a4d0/src/vaadin-radio-group.html#L188)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

This functionality of `readonly` state seems unusual to me. Do we really need to implement it? There is no such functionality in `paper-radio-group` or on MDN specification for `radiogroup`: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/radiogroup .
</blockquote></details>

we have readonly in all our components, and flow expects that all form elements that hasValue implements that, otherwise they offer an API that wouldn't work

https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L193

They already expects that their `VaadinRadioGroup` follows this API because they extend the `AbstractField` which eventually implements `HasValue`

https://github.com/vaadin/vaadin-radio-button-flow/blob/master/src/main/java/com/vaadin/flow/component/radiobutton/GeneratedVaadinRadioGroup.java#L73

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67)*

**Comment by manolo** [comment]
Review status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @YuriyVaadin and @manolo)

---

*[src/vaadin-radio-group.html, line 202 at r1](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67#-LG4VXHQEsy2lNSSLvAG:-LG55EEt4BWcg0vBpV_P:b1mzy52) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/bd5014d79598ad43f421c140907cfcf67326a4d0/src/vaadin-radio-group.html#L202)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Nit: untested code.
</blockquote></details>

Actually unneeded code since radiobutton disabled already takes care of it.
Added tests to demonstrate the feature
Done.

---

*[src/vaadin-radio-group.html, line 281 at r1](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67#-LG4VgjQ8pc0KotV-SvI:-LG5AupM7NbwWlTcCbvi:b-896fjx) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/bd5014d79598ad43f421c140907cfcf67326a4d0/src/vaadin-radio-group.html#L281)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Nit: untested code.
</blockquote></details>

Done

---

*[src/vaadin-radio-group.html, line 295 at r1](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67#-LG4Vpg_1c19i1cz-IjO:-LG5Cp3n7bwNaLeeIN5I:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/bd5014d79598ad43f421c140907cfcf67326a4d0/src/vaadin-radio-group.html#L295)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Nit: untested code.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67)*

**Comment by YuriyVaadin** [comment]
Reviewed 3 of 3 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67)*

**Comment by tomivirkki** [comment]
*[demo/radio-group-demos.html, line 32 at r4](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67#-LG9jyux4Qx5aU-qb0bN:-LG9jyux4Qx5aU-qb0bO:b-tvh8w1) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/badbaeebd5a2a6db81c1072d857aad7faed36f4e/demo/radio-group-demos.html#L32)):*
> ```HTML
>     </vaadin-demo-snippet>
> 
>     <h3>Validation</h3>
> ```

I don't see how this demonstrates the feature as there's no way to select an invalid option. Maybe we should just add "required error-message='Something....'" to the "Radio Group with Iron Form" where the group is validated on Submit

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67)*

**Comment by manolo** [comment]
Review status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @YuriyVaadin and @manolo)

---

*[demo/radio-group-demos.html, line 32 at r4](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67#-LG9jyux4Qx5aU-qb0bN:-LG9pEfh9ldMHDUpzQYo:b-ov8zam) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/badbaeebd5a2a6db81c1072d857aad7faed36f4e/demo/radio-group-demos.html#L32)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I don't see how this demonstrates the feature as there's no way to select an invalid option. Maybe we should just add "required error-message='Something....'" to the "Radio Group with Iron Form" where the group is validated on Submit
</blockquote></details>

If you visit wit keyboard tab it shows on focus out.
Will try to make a better demo, as you indicate iron form might be the most appropriate to reuse

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67)*

**Comment by manolo** [comment]
Review status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @YuriyVaadin and @manolo)

---

*[demo/radio-group-demos.html, line 32 at r4](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67#-LG9jyux4Qx5aU-qb0bN:-LGA28ZU873VwLTl_x5i:bniah3f) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/badbaeebd5a2a6db81c1072d857aad7faed36f4e/demo/radio-group-demos.html#L32)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

If you visit wit keyboard tab it shows on focus out.
Will try to make a better demo, as you indicate iron form might be the most appropriate to reuse
</blockquote></details>

Moved validation to iron-form demos. At the same time adding real case label, names and values to other demos.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 12 files at r4, 11 of 11 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/67)*

**Pull request merged**
