### PR TITLE
Restored value property

### PR DESCRIPTION
**Pull request by Toshegg**
Connects to #15 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button/22)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-radio-group.html, line 84 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22#-KxrwBzZCAIRvhCird9q:-KxrwBzZCAIRvhCird9r:b-fnr8sp) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/49284241d95b3786cfddb5d9a3597b27f70961ad/vaadin-radio-group.html#L84)):*
> ```HTML
>             value: {
>               type: String,
>               reflectToAttribute: true,
> ```

Shouldn't reflect to attribute

---

*[test/vaadin-radio-group.html, line 153 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22#-Kxrx7HGvyuoDJfLn03Y:-Kxrx7HGvyuoDJfLn03Z:b1c2y87) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/49284241d95b3786cfddb5d9a3597b27f70961ad/test/vaadin-radio-group.html#L153)):*
> ```HTML
>       it('should check proper button when value is setted', () => {
>         vaadinRadioButtonGroup.value = '2';
>         
> ```

nit: spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22)*

**Comment by Toshegg** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-radio-group.html, line 84 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22#-KxrwBzZCAIRvhCird9q:-Kxrze4_ZzaqcHDK-Fm3:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/49284241d95b3786cfddb5d9a3597b27f70961ad/vaadin-radio-group.html#L84)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Shouldn't reflect to attribute
</blockquote></details>

Done.

---

*[test/vaadin-radio-group.html, line 153 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22#-Kxrx7HGvyuoDJfLn03Y:-Kxrzef6sDL1HSpTjctl:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/49284241d95b3786cfddb5d9a3597b27f70961ad/test/vaadin-radio-group.html#L153)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

nit: spaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-radio-button.html, line 136 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22#-KxrqeEhKL09Ut4-2pRa:-KxrqeEhKL09Ut4-2pRb:b1c2y87) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/49284241d95b3786cfddb5d9a3597b27f70961ad/vaadin-radio-button.html#L136)):*
> ```HTML
>         constructor() {
>           super();
>           
> ```

nit: spaces

---

*[test/vaadin-radio-group.html, line 153 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22#-KxrqRQZHU7APOLiAtu5:-KxrqRQZHU7APOLiAtu6:b-xx2utv) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/49284241d95b3786cfddb5d9a3597b27f70961ad/test/vaadin-radio-group.html#L153)):*
> ```HTML
>       it('should check proper button when value is setted', () => {
>         vaadinRadioButtonGroup.value = '2';
>         
> ```

nit:  extra spaces here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22)*

**Comment by Toshegg** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-radio-button.html, line 136 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22#-KxrqeEhKL09Ut4-2pRa:-Kxs-PS0V2WE3MisHP0A:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/49284241d95b3786cfddb5d9a3597b27f70961ad/vaadin-radio-button.html#L136)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

nit: spaces
</blockquote></details>

Done.

---

*[test/vaadin-radio-group.html, line 153 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22#-KxrqRQZHU7APOLiAtu5:-Kxs-Q4Gh5OA6Cq0xKaJ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/49284241d95b3786cfddb5d9a3597b27f70961ad/test/vaadin-radio-group.html#L153)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

nit:  extra spaces here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22)*

**Comment by tomivirkki** [comment]
*[vaadin-radio-group.html, line 219 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22#-Kxs1MAxmPLUX_WsS0uW:-Kxs1MAxmPLUX_WsS0uX:bc1pc5w) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/e4f7cf1ea674caaef133782d9628730538df6509/vaadin-radio-group.html#L219)):*
> ```HTML
>               this._selectButton(newCheckedButton);
>             } else {
>               console.warn('There is no nested button which value suits setted one.');
> ```

Rephrase to "No <vaadin-radio-button> with value ${newV} found."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22)*

**Comment by tomivirkki** [comment]
*[vaadin-radio-group.html, line 219 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22#-Kxs1MAxmPLUX_WsS0uW:-Kxs1pddCJwDxMHvRNuT:bjdzo5w) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/e4f7cf1ea674caaef133782d9628730538df6509/vaadin-radio-group.html#L219)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Rephrase to "No <vaadin-radio-button> with value ${newV} found."
</blockquote></details>

Rephrase to `No <vaadin-radio-button> with value ${newV} found.`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22)*

**Comment by Toshegg** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-radio-group.html, line 219 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22#-Kxs1MAxmPLUX_WsS0uW:-KxvcC6veOB4w1m_nQg1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/e4f7cf1ea674caaef133782d9628730538df6509/vaadin-radio-group.html#L219)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Rephrase to `No <vaadin-radio-button> with value ${newV} found.`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22)*

**Comment by Toshegg** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-radio-group.html, line 219 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22#-Kxs1MAxmPLUX_WsS0uW:-Kxvgua_R1_zZvCee2bS:b-jlmulw) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/e4f7cf1ea674caaef133782d9628730538df6509/vaadin-radio-group.html#L219)):*
<details><summary><i>Previously, Toshegg wrote…</i></summary><blockquote>

Done.
</blockquote></details>

FYI: [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) is not supported in IE11. Changed to concatenation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22)*

**Comment by tomivirkki** [comment]
*[vaadin-radio-group.html, line 219 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22#-Kxs1MAxmPLUX_WsS0uW:-Kxvhn-f-EANUyHjF5QG:bvulpeb) ([raw file](https://github.com/vaadin/vaadin-radio-button/blob/e4f7cf1ea674caaef133782d9628730538df6509/vaadin-radio-group.html#L219)):*
<details><summary><i>Previously, Toshegg wrote…</i></summary><blockquote>

FYI: [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) is not supported in IE11. Changed to concatenation.
</blockquote></details>

Template literals are ok. The element is written in es6 so it's transpiled for IE11 anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22#-:-Kxwcw8-H2zhB3OygkBt:bnfp4nl)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22#-:-KxwdH8Swukk8ijc3aMr:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button/22#-:-KxwfGRWRrqI2xF02HfC:bnfp4nl)*

**Pull request merged**
